### ISSUE TITLE
[Suggestion] Heroku

### ISSUE THREAD

**Issue by ilovefreesw** [ciccionamente/WeExpire#1]
Add Deploy to Heroku button in README to host it for free in 1 click.

https://devcenter.heroku.com/articles/heroku-button

**Comment by ciccionamente** [comment]
Thanks @ilovefreesw for your suggestion. I'll mark this issue as closed because till now we haven't received similar requests. Also, if we decide to include Heroku we should also consider to include other services such as Azure, Vercel, etc.
