### ISSUE TITLE
Using Docker-Compose: TCPDF ERROR

### ISSUE THREAD

**Issue by RdeLange** [ciccionamente/WeExpire#11]
I am using Docker compose to get weexpire running, but when creating the pdf I get the following error:
TCPDF ERROR: TCPDF requires the Imagick or GD extension to handle PNG images with alpha channel.

Probably the GD extension is not installed in the container. I guess this can be fixed by adding the following line in the DockeFile:
RUN docker-php-ext-install gd

**Comment by ciccionamente** [comment]
Hi @RdeLange, thanks for your feedback! @wolveix, I remember that you worked on #9 - do you think this is something that can be included in order to avoid such case?

**Comment by wolveix** [comment]
Just pushed a PR to resolve this issue, appreciate you highlighting this issue @RdeLange, and I appreciate the tag @ciccionamente! Apologies for the oversight in the initial implementation 😅

**Comment by ciccionamente** [comment]
Thank you so much @wolveix for taking care of it so quickly! @RdeLange the issue you discovered should be fixed.
